config/routes.rb
Bewerbungsclip28012013::Application.routes.draw do

  resources :templates
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :bessions, only: [:new, :create, :destroy]

  match '/signuptemplate',  to: 'templates#new'
  match '/signouttemplate', to: 'bessions#destroy', via: :delete

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'bessions#new'
    
  match "/tour", to: 'static_pages#tour'
  match "/preise", to: 'static_pages#preise'
  match "/wissen", to: 'static_pages#wissen'
  match "/haftungsausschluss", to: 'static_pages#haftungsausschluss'
  match "/impressum", to: 'static_pages#impressum'

end

app/controllers/bessions_controller.rb
class BessionsController < ApplicationController

  def new
  end

  def create
    template = Template.find_by_bosskey(params[:bession][:bosskey])
    if template
      sign_in template
      redirect_back_or template
    else
      flash.now[:error] = 'Dieses Kennwort ist nicht vergeben. Bitte kontrollieren Sie die Eingabe.'
      render 'new'
    end
  end

  def destroy
    tsign_out
    redirect_to root_url
  end
end

app/helpers/bessions_helper.rb
module BessionsHelper

	def tsign_in(template)
		cookies.permanent[:remember_token] = template.remember_token
		self.current_template = template
	end

	def tsigned_in?
    	!current_template.nil?
	end

	def current_template=(template)
    	@current_template = template
 	end

 	def current_template
    	@current_template ||= Template.find_by_remember_token(cookies[:remember_token])
	end

	def tsign_out
    	self.current_template = nil
    	cookies.delete(:remember_token)
	end
end

app/views/bessions/new.html.erb
<% if signed_in? %>
  <div class="banner">
    <div class="container">
    
      <div class="row sessions-end-row">
        <div class="span3 offset4 sessions-end-box center">
          <p id="bosslogin">Bitte <%= link_to "melde dich ab", signout_path, method: "delete" %> um deinen BewerbungsClip mit dem Kennwort anzusehen.</p>
            <%= link_to "Abmelden", signout_path, method: "delete", class: "btn btn-large btn-success btn-form" %>
        </div>
      </div>

    </div>
  </div>

<% else %>
  <div class="banner">
    <div class="container">

      <div class="row">
        <h1 id="startseite_h1">Darf ich mich vorstellen?!</h1>
        <h2 id="startseite_h2">Mein persönlicher BewerbungsClip:</h2>
      </div>
    
      <div class="row ">
          <div class="span4 offset7 boss-box">
            <p id="bosslogin">Geben Sie hier Ihr Kennwort ein</p></br>
          <%= form_for(:bession, url: bessions_path) do |f| %>
            <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>">
                  <%= value %>
                </div>
              <% end %>

            <%= f.text_field :bosskey, placeholder: "Kennwort", autofocus: true, class: "kennwort-field" %>

            <%= f.submit "BewerbungsClip ansehen", class: "btn btn-large btn-success btn-form" %>
          <% end %>
          </div>
      </div>

    </div>
  </div>

<% end %>