config/routes.rb
Bewerbungsclip28012013::Application.routes.draw do

  resources :templates
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :bessions, only: [:new, :create, :destroy]

  match '/signuptemplate',  to: 'templates#new'
  match '/signouttemplate', to: 'bessions#destroy', via: :delete

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'bessions#new'
    
  match "/tour", to: 'static_pages#tour'
  match "/preise", to: 'static_pages#preise'
  match "/wissen", to: 'static_pages#wissen'
  match "/haftungsausschluss", to: 'static_pages#haftungsausschluss'
  match "/impressum", to: 'static_pages#impressum'

end

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% key1 = ('0'..'9').to_a.shuffle.first(10).join %>
  <% if @template.errors.any? %>
    <div class="span6">
      <div id="error_explanation" class="span5">
        <h4><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h4>

        <ul>
        <% @template.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="span6">

    <div class="field">
      <%= f.hidden_field :user_id, value: params[:user_id] %>
    </div>

    <div class="field">
      <%= f.hidden_field :vorname, value: params[:vorname] %>
    </div>

    <div class="field">
      <%= f.hidden_field :nachname, value: params[:nachname] %>
    </div>

    <div class="field">
      <%= f.hidden_field :fingerprint, value: params[:fingerprint] %>
    </div>

    <div class="field">
      <%= f.hidden_field :password, value: key1 %>
    </div>

    <div class="field">
      <%= f.hidden_field :password_confirmation, value: key1 %>
    </div>

    <div class="field">
      <%= f.hidden_field :bosskey, value: key1 %>
    </div>

    <div class="span5 field margin-top-15 ">
      <%= f.label :for_company, "Name", title: "Gib deinem BewerbungsClip einen Namen, damit du dich auch später noch gut auskennst. Nur du kannst diesen Namen sehen." %>
      <%= f.text_field :for_company, placeholder: "Firmenname", title: "Gib deinem BewerbungsClip einen Namen, damit du dich auch später noch gut auskennst. Nur du kannst diesen Namen sehen." %>
    </div>

    <div class="span5 field margin-top-15">
      <%= f.file_field :video %>
    </div>

    <div class="span2">
      <%= f.submit "Profil erstellen", class: "btn btn-large btn-warning btn-form" %>
    </div>
<% end %>

    <div class="span1">
      <%= link_to 'abbrechen', templates_path, class: "btn btn-large btn-form" %>
    </div>

  </div>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<div class="banner">
</div>
  <div class="container">

    <div class="row templates-show-row">
      <div class="span12 user-show-box">
        <div class="span11">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>">
              <%= value %>
            </div>
          <% end %>
        </div>

    <% if @user.templates.any? %>
      <div class="span12">
        <h2>Übersicht</h2><br>
      </div>

      <div class="span5 el1">
        <h4>BewerbungsClip für</h4>
      </div>
      <div class="span2 el2">
        <h4>Kennwort</h4>
      </div>
      <div class="span1 el3">
        <h4>besucht</h4>
      </div>
      <div class="span2 el4">
        <h4>zuletzt</h4>
      </div>

    <% else %>
      <div class="span12">
        <h2>Erstelle dein erstes Profil hier:</h2>
      </div>
    <% end %>

        <% @user.templates.each do |template| %>

          <div class="span5 el1">
            <h5><%= template.for_company %>
              <% if template.for_company.empty? %>Allgemeines Profil<% end %></h5>
          </div>
          <div class="span2 el2">
            <h5><%= template.bosskey %></h5>
          </div>
          <div class="span1 el3">
            <h5><%= ('0'..'9').to_a.shuffle.first(1).join %> mal</h5>
          </div>
          <div class="span2 el4">
            <h5><%= template.created_at.strftime("%d.%m. %Rh") %></h5>
          </div>
          <div class="span3 special el5">
            <%= link_to 'anzeigen', template, class: "btn btn-small btn-primary size" %>
            <%= link_to 'löschen', template, class: "btn btn-small btn-danger size", method: :delete, data: { confirm: 'Willst du das Profil wirklich unwiderruflich löschen?' } %>
          </div>
          
        <% end %><br>

      <div class="span6">
      <%= link_to 'neues Profil erstellen', new_template_path(user_id: @user.id, vorname: @user.vorname, nachname: @user.nachname, fingerprint: @user.fingerprint), class: "btn btn-large btn-warning btn-form" %>
      </div>
      </div>
    </div>
  </div>

app/views/templates/index_error.html.erb
<% provide(:title, @user.name) %>
<div class="banner">
</div>
  <div class="container">

    <div class="row templates-show-row">
      <div class="span12 user-show-box">
        <div class="span11">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>">
              <%= value %>
            </div>
          <% end %>
        </div>

    <% if @user.templates.any? %>
      <div class="span12">
        <h2>Übersicht</h2><br>
      </div>

      <div class="span5 el1">
        <h4>BewerbungsClip für</h4>
      </div>
      <div class="span2 el2">
        <h4>Kennwort</h4>
      </div>
      <div class="span1 el3">
        <h4>besucht</h4>
      </div>
      <div class="span2 el4">
        <h4>zuletzt</h4>
      </div>

    <% else %>
      <div class="span12">
        <h2>Erstelle dein erstes Profil hier:</h2>
      </div>
    <% end %>

        <% @user.templates.each do |template| %>

          <div class="span5 el1">
            <h5><%= template.for_company %>
              <% if template.for_company.empty? %>Allgemeines Profil<% end %></h5>
          </div>
          <div class="span2 el2">
            <h5><%= template.bosskey %></h5>
          </div>
          <div class="span1 el3">
            <h5><%= ('0'..'9').to_a.shuffle.first(1).join %> mal</h5>
          </div>
          <div class="span2 el4">
            <h5><%= template.created_at.strftime("%d.%m. %Rh") %></h5>
          </div>
          <div class="span3 special el5">
            <%= link_to 'anzeigen', template, class: "btn btn-small btn-primary size" %>
            <%= link_to 'löschen', template, class: "btn btn-small btn-danger size", method: :delete, data: { confirm: 'Willst du das Profil wirklich unwiderruflich löschen?' } %>
          </div>
          
        <% end %><br>

      <div class="span6">
      <%= link_to 'neues Profil erstellen', new_template_path(user_id: @user.id, vorname: @user.vorname, nachname: @user.nachname, fingerprint: @user.fingerprint), class: "btn btn-large btn-warning btn-form" %>
      </div>
      </div>
    </div>
  </div>

app/views/templates/new.html.erb
<% provide(:title, 'Template erstellen') %>
<div class="banner">
	<div class="container">
		<div class="row template-create-row">
			<div class="span6 offset3 template-create-box">
				<div class="span6">
					<div class="span5">
						<h1>Neues Profil erstellen</h1>
					</div>
				</div>
				
				<%= render 'form' %>
				
			</div>
		</div>
	</div>
</div>

app/views/templates/show.html.erb
<div class="banner">
	<div class="container">

		<div class="row template-show-row">
			<div class="span10 offset1 template-show-box">

				<% flash.each do |key, value| %>
			    <div class="alert alert-<%= key %>">
			    	<%= value %>
			    </div>
			  	<% end %>

			  	<h3 class="center showtemplate-style">
			  	BewerbungsClip von <%= "#{@template.vorname} #{@template.nachname}" %></h3>

			    <div class="video center">
			      <%= video_tag @template.video, size: "570x500", controls: true %>
			    </div>

			</div>
		</div>
		<div class="row button-down">
			<div clas="span2">
				<% if signed_in? %>
					<% if current_user.fingerprint == @template.fingerprint %>
					<%= link_to 'zurück', templates_path, class: "btn btn-large btn-form" %>
					<% end %>
				<% end %>

			</div>
		</div>

	</div>
</div>