config/routes.rb
Bewerbungsclip28012013::Application.routes.draw do

  resources :templates
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :bessions, only: [:new, :create, :destroy]

  match '/signuptemplate',  to: 'templates#new'
  match '/signouttemplate', to: 'bessions#destroy', via: :delete

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'bessions#new'
    
  match "/tour", to: 'static_pages#tour'
  match "/preise", to: 'static_pages#preise'
  match "/wissen", to: 'static_pages#wissen'
  match "/haftungsausschluss", to: 'static_pages#haftungsausschluss'
  match "/impressum", to: 'static_pages#impressum'

end

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <nav>
    <ul>
      <li><%= link_to "Haftungsausschluss", haftungsausschluss_path %></li>
      <li><%= link_to "Impressum & Kontakt", impressum_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner ">
  	<div class="container">
     <nav>
       <ul class="nav pull-right">
<% if tsigned_in? %>
  <li><%= link_to "zum BewerbungsClip", current_template %></li>
  <li><%= link_to "Abmelden", signouttemplate_path, method: "delete"  %></li>
<% else %>

         <li><%= link_to "Startseite",    root_path %></li>
         <li><%= link_to "Tour",    tour_path %></li>
         <li><%= link_to "Preise", preise_path %></li>
         <li><%= link_to "Bewerbungstipps", wissen_path %></li>
         
  <% if signed_in? %>
      <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= "#{current_user.vorname} #{current_user.nachname}"%> <b class="caret"></b>
        </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", templates_path %></li>
              <li><%= link_to "Einstellungen", current_user %></li>
              <li><%= link_to "Konto freischalten", '#' %></li>
          <% if current_user.admin == true %>
            <li><%= link_to "Userindex", users_path %></li>
          <% end %>
              <li class="divider"></li>
              <li><%= link_to "Abmelden", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
  <% else %>
      <%= link_to 'Registrieren', signup_path, class: "btn btn-mini btn-success", id: "btn-login"%>
      <%= link_to 'Login', signin_path, class: "btn btn-mini", id: "btn-login"%>
  <% end %>
<% end %>

       </ul>
     </nav>
   </div>
 </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <link href="http://fonts.googleapis.com/css?family=Ubuntu:bold" rel="stylesheet" type="text/css">
	<script type="text/javascript" src="//use.typekit.net/swq7iai.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body>
	<%= render 'layouts/navbar' %>

	<%= yield %>

	<%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>